### ISSUE TITLE
Driver ovh v3 not suported

### ISSUE THREAD

**Issue by clementGestadis** [sausin/laravel-ovh#20]
Hi!,

I managed to configure the driver for version 2.0 of the API ovh. Currently they will go to version 3 of their API, and the impossible to configure the drive. Is it compatible with this version?

Thank you for your answers

**Comment by sausin** [comment]
@clementGestadis thank you for the info!

Could you please share some links?

**Comment by sausin** [comment]
@clementGestadis could you give the latest release a spin?

If all is good, I'll close the issue.

**Comment by iksaku** [comment]
Just tested v3 of this package, can confirm that Identity v3 is working properly

**Comment by sausin** [comment]
@iksaku excellent! Closing this issue :+1:
