### ISSUE TITLE
Need better documentation on configuration

### ISSUE THREAD

**Issue by olivM** [sausin/laravel-ovh#35]
Hi,
thanks for this package !

but i should say i've had a hard time finding the right values for OVH_URL and OVH_ENDPOINT

can you had explanation on where to find thoses 2 values ?
OVH_URL => https://auth.cloud.ovh.net/v3/ ( i guess only for tag v3.* )
OVH_ENDPOINT=https://storage.[region].cloud.ovh.net/v1/AUTH_[project_id]/[container_id]

thanks again

**Comment by olivM** [comment]
also
OVH_REGION => must be be uppercase

**Comment by sausin** [comment]
@olivM Sure! I'll update the documentation with suggestions and how to get the values! :+1:

**Comment by sausin** [comment]
@olivM Let me know if the PR is satisfactory.

**Comment by olivM** [comment]
it's great !

**Comment by sausin** [comment]
The update is online, thanks for the help!
