### ISSUE TITLE
supprt php7.2.2

### ISSUE THREAD

**Issue by kslr** [sausin/laravel-ovh#4]
php-opencloud/openstack v2.1.4 requires php >=7.0 <7.2 -> your PHP version (7.2.2) does not satisfy that requirement.

> Due to new object typehint since PHP 7.2, Object is a reserved keyword thus class -OpenStack\ObjectStore\v1\Models\Object had to be renamed to -OpenStack\ObjectStore\v1\Models\StorageObject. See #184 for details.

https://github.com/php-opencloud/openstack/pull/184

So should a new branch support be established?
Can I submit v2?

**Comment by kslr** [comment]
#5

**Comment by sausin** [comment]
@kslr thanks! As mentioned to #5, #3 submitted prior was merged.
