### ISSUE TITLE
Add cache option?

### ISSUE THREAD

**Issue by wfeller** [sausin/laravel-ovh#51]
Would you be interested in adding a cache feature to the package?

See:
- https://github.com/illuminate/filesystem/blob/8eaa230711347ac76b3b61372d1b3b332e0931ee/FilesystemManager.php#L240
- https://laravel.com/docs/7.x/filesystem#caching

In this case, I could submit a PR.

**Comment by iksaku** [comment]
Looks pretty interesting, candidate feature for a `v5.2` release, maybe we could pack that with #48 if PRs are merged simultaneously

**Comment by iksaku** [comment]
More info on [Fly system’s Caching Docs](https://flysystem.thephpleague.com/v1/docs/advanced/caching/)
