### ISSUE TITLE
Laravel 5.8 support

### ISSUE THREAD

**Issue by Dimidel** [sausin/laravel-ovh#6]
Hi,
Laravel 5.8 support has been added 4 days ago (release 2.0.2) but not yet available on composer.
Consequently, "composer requires sausin/laravel-ovh" command causes error on Laravel 5.8.
Thank you

**Comment by sausin** [comment]
@Dimidel it should be fixed now. Can you try again?

**Comment by Dimidel** [comment]
It's perfect now !
Thank you @sausin
