### ISSUE TITLE
Package Incompatability with Laravel 8.0 

### ISSUE THREAD

**Issue by Roken120** [sausin/laravel-ovh#82]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install laravel/framework v8.42.1
    - Conclusion: don't install laravel/framework v8.42.0
    - Installation request for sausin/laravel-ovh ^4.1 -> satisfiable by sausin/laravel-ovh[v4.1.0].
    - Installation request for laravel/framework (locked at v8.41.0, required as ^8.0.0) -> satisfiable by laravel/framework[v8.41.0].
    - Can only install one of: laravel/framework[8.x-dev, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.0.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.0.1, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.0.2, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.0.3, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.0.4, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.1.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.10.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.11.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.11.1, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.11.2, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.12.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.12.1, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.12.2, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.12.3, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.13.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.14.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.15.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.16.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.16.1, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.17.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.17.1, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.17.2, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.18.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.18.1, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.19.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.2.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.20.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.20.1, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.21.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.22.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.22.1, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.23.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.23.1, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.24.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.25.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.26.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.26.1, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.27.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.28.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.28.1, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.29.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.3.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.30.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.30.1, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.31.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.32.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.32.1, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.33.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.33.1, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.34.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.35.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.35.1, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.36.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.36.1, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.36.2, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.37.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.38.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.39.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.4.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.40.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.41.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.5.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.6.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.7.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.7.1, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.8.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[v8.9.0, 5.7.x-dev].
    - Can only install one of: laravel/framework[5.7.x-dev, v8.41.0].
    - Can only install one of: laravel/framework[5.7.x-dev, v8.41.0].
    - Conclusion: install laravel/framework 5.7.x-dev
    - Installation request for laravel/framework ^8.0.0 -> satisfiable by laravel/framework[8.x-dev, v8.0.0, v8.0.1, v8.0.2, v8.0.3, v8.0.4, v8.1.0, v8.10.0, v8.11.0, v8.11.1, v8.11.2, v8.12.0, v8.12.1, v8.12.2, v8.12.3, v8.13.0, v8.14.0, v8.15.0, v8.16.0, v8.16.1, v8.17.0, v8.17.1, v8.17.2, v8.18.0, v8.18.1, v8.19.0, v8.2.0, v8.20.0, v8.20.1, v8.21.0, v8.22.0, v8.22.1, v8.23.0, v8.23.1, v8.24.0, v8.25.0, v8.26.0, v8.26.1, v8.27.0, v8.28.0, v8.28.1, v8.29.0, v8.3.0, v8.30.0, v8.30.1, v8.31.0, v8.32.0, v8.32.1, v8.33.0, v8.33.1, v8.34.0, v8.35.0, v8.35.1, v8.36.0, v8.36.1, v8.36.2, v8.37.0, v8.38.0, v8.39.0, v8.4.0, v8.40.0, v8.41.0, v8.42.0, v8.42.1, v8.5.0, v8.6.0, v8.7.0, v8.7.1, v8.8.0, v8.9.0].

**Comment by iksaku** [comment]
Support for Laravel 8 has been released as of [v5.4](https://github.com/sausin/laravel-ovh/releases/tag/v5.4.0) of this package, and PHP 8 support has been included as of the latest release ([v6.0](https://github.com/sausin/laravel-ovh/releases/tag/v6.0.0)).

As per the log you posted, you're trying to install Laravel v8 while still requiring this package's v4.1.

**Comment by Roken120** [comment]
Hello,
I have he works :) maybe i have this error : 
Class 'League\Flysystem\Cached\CachedAdapter' not found
I have try to install League/flysystem maybe i have this error this time: 

  Problem 1
    - nimbusoft/flysystem-openstack-swift 0.3.4 requires league/flysystem ^1.0 -> satisfiable by league/flysystem[1.0.x-dev, 1.x-dev].
    - nimbusoft/flysystem-openstack-swift 0.3.4 requires league/flysystem ^1.0 -> satisfiable by league/flysystem[1.0.x-dev, 1.x-dev].
    - nimbusoft/flysystem-openstack-swift 0.3.4 requires league/flysystem ^1.0 -> satisfiable by league/flysystem[1.0.x-dev, 1.x-dev].
    - Can only install one of: league/flysystem[2.0.0, 1.x-dev].
    - Can only install one of: league/flysystem[2.0.0, 1.0.x-dev].
    - Installation request for league/flysystem 2 -> satisfiable by league/flysystem[2.0.0].
    - Installation request for nimbusoft/flysystem-openstack-swift (locked at 0.3.4) -> satisfiable by nimbusoft/flysystem-openstack-swift[0.3.4].

**Comment by sausin** [comment]
Looks like an error related to incorrectly cached adapter. In all of my tests, the package seems to be working fine with Laravel v8.x

If you still have any issues, feel free to ping again!
