### ISSUE TITLE
Laravel 9

### ISSUE THREAD

**Issue by wfeller** [sausin/laravel-ovh#84]
Hey, can you update the Laravel version? Thanks

**Comment by sausin** [comment]
Things have been super hectic at my end. Need a few minutes to get this going.

If someone could resolve a few issues in #85

**Comment by wfeller** [comment]
I'll look at this over the weekend 👍

**Comment by sausin** [comment]
This was added in another PR to help with CI

@iksaku would it be possible for you please help out with this part?

**Comment by sausin** [comment]
Merged, thanks a lot for your efforts @wfeller
